"""add_pronunciation_tables

Revision ID: 428244644432
Revises: ca42c89bd609
Create Date: 2026-04-24 20:55:00.603271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '428244644432'
down_revision: Union[str, None] = 'ca42c89bd609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vowel_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('consonant_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fluency_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('intelligibility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('summary_feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase_pronunciations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('phrase_text', sa.String(length=500), nullable=False),
    sa.Column('phrase_index', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vowel_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('consonant_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fluency_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('intelligibility_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('phoneme_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['pronunciation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrase_pronunciations')
    op.drop_table('pronunciation_sessions')
    # ### end Alembic commands ###
