"""add_accentuation_tables

Revision ID: ca42c89bd609
Revises: 20627f7c8ace
Create Date: 2026-04-23 20:35:08.583762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca42c89bd609'
down_revision: Union[str, None] = '20627f7c8ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accentuation_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pronunciation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rhythm_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('intonation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('stress_accuracy_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('summary_feedback', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phrase_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('phrase_text', sa.String(length=500), nullable=False),
    sa.Column('phrase_index', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pronunciation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rhythm_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('intonation_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('stress_accuracy_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('specific_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['accentuation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phrase_evaluations')
    op.drop_table('accentuation_sessions')
    # ### end Alembic commands ###
